# Generated by Django 4.0.1 on 2022-01-30 07:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('modified_status_date', models.DateField()),
                ('status', models.TextField()),
                ('type', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False, unique=True)),
                ('is_main', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
