# Generated by Django 4.0.1 on 2022-01-30 07:58

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ok_link',
            field=models.URLField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_link',
            field=models.URLField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Moscow'),
        ),
        migrations.AddField(
            model_name='client',
            name='viber_link',
            field=models.URLField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[core.validators.validate_client_id]),
        ),
        migrations.CreateModel(
            name='VkSocialNetwork',
            fields=[
                ('link', models.URLField(blank=True, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FbSocialNetwork',
            fields=[
                ('link', models.URLField(blank=True, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
