# Generated by Django 4.0.1 on 2022-01-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_instagram_link_client_ok_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Активный'), ('Inactive', 'Не активный')], default='Active', max_length=10),
        ),
    ]
