# Generated by Django 4.0.1 on 2022-01-30 08:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[core.validators.validate_legal_person_id])),
                ('create_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('full_title', models.CharField(max_length=50)),
                ('short_title', models.CharField(max_length=10)),
                ('inn', models.IntegerField(max_length=12)),
                ('kpp', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Unknown', 'Неизвестно')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Активен'), ('Inactive', 'Не активен')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('Primary', 'Первичный'), ('Repeated', 'Повторный'), ('External', 'Внешний'), ('Indirect', 'Косвенный')], default='Primary', max_length=10),
        ),
    ]
