# Generated by Django 4.0.1 on 2022-01-30 08:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_legalperson_inn_alter_legalperson_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalperson',
            name='inn',
            field=models.CharField(max_length=12, validators=[core.validators.validate_inn]),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='kpp',
            field=models.CharField(max_length=9, validators=[core.validators.validate_kpp]),
        ),
    ]
