# Generated by Django 4.0.1 on 2022-01-30 08:56

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_legalperson_inn_alter_legalperson_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[core.validators.validate_client_id], verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='client',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=128, unique=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_date',
            field=models.DateField(verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_status_date',
            field=models.DateField(verbose_name='Дата изменения статуса'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ok_link',
            field=models.URLField(blank=True, max_length=128, unique=True, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(max_length=30, verbose_name='Отечество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Unknown', 'Неизвестно')], default='Unknown', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Активен'), ('Inactive', 'Не активен')], default='Active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_link',
            field=models.URLField(blank=True, max_length=128, unique=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('Primary', 'Первичный'), ('Repeated', 'Повторный'), ('External', 'Внешний'), ('Indirect', 'Косвенный')], default='Primary', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='client',
            name='viber_link',
            field=models.URLField(blank=True, max_length=128, unique=True, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=128, unique=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='create_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='full_title',
            field=models.CharField(max_length=50, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[core.validators.validate_legal_person_id], verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='inn',
            field=models.CharField(max_length=12, validators=[core.validators.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='kpp',
            field=models.CharField(max_length=9, validators=[core.validators.validate_kpp], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='modified_date',
            field=models.DateField(verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='short_title',
            field=models.CharField(max_length=10, verbose_name='Сокращенное название'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[core.validators.validate_department_id], verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент')),
                ('legal_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legalperson', verbose_name='Юридическое лицо')),
            ],
        ),
    ]
