# Generated by Django 4.0.1 on 2022-01-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_client_created_date_alter_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='client',
        ),
        migrations.AddField(
            model_name='department',
            name='client',
            field=models.ManyToManyField(to='core.Client', verbose_name='Клиент'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='legal_person',
        ),
        migrations.AddField(
            model_name='department',
            name='legal_person',
            field=models.ManyToManyField(to='core.LegalPerson', verbose_name='Юридическое лицо'),
        ),
    ]
