# Generated by Django 4.0.1 on 2022-01-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_department_client_department_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=128, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ok_link',
            field=models.URLField(blank=True, max_length=128, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_link',
            field=models.URLField(blank=True, max_length=128, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=128, verbose_name='WhatsApp'),
        ),
    ]
