# Generated by Django 4.0.1 on 2022-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_client_instagram_link_alter_client_ok_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='modified_date',
            field=models.DateField(blank=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_status_date',
            field=models.DateField(blank=True, verbose_name='Дата изменения статуса'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='modified_date',
            field=models.DateField(blank=True, verbose_name='Дата изменения'),
        ),
    ]
