# Generated by Django 4.0.1 on 2022-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_client_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='viber_link',
            field=models.URLField(blank=True, max_length=128, verbose_name='Viber'),
        ),
    ]
