# Generated by Django 4.0.1 on 2022-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_client_viber_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='modified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_status_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения статуса'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='modified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
