# Generated by Django 4.0.1 on 2022-01-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_client_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AlterModelOptions(
            name='legalperson',
            options={'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),
    ]
