# Generated by Django 4.0.1 on 2022-01-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contact_options_alter_contact_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbsocialnetwork',
            options={'verbose_name': 'Facebook'},
        ),
        migrations.AlterModelOptions(
            name='vksocialnetwork',
            options={'verbose_name': 'Вконтакте'},
        ),
        migrations.AlterField(
            model_name='fbsocialnetwork',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='vksocialnetwork',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент'),
        ),
    ]
