# Generated by Django 4.0.1 on 2022-01-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_fbsocialnetwork_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbsocialnetwork',
            options={'verbose_name': 'Facebook', 'verbose_name_plural': 'Facebook'},
        ),
        migrations.AlterModelOptions(
            name='vksocialnetwork',
            options={'verbose_name': 'Вконтакте', 'verbose_name_plural': 'Вконтакте'},
        ),
    ]
