# Generated by Django 4.0.1 on 2022-01-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_fbsocialnetwork_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='client',
            field=models.ManyToManyField(related_name='departments', to='core.Client', verbose_name='Клиент'),
        ),
    ]
