# Generated by Django 4.0.1 on 2022-01-30 11:06

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_department_parent_alter_department_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.IntegerField(default=1, validators=[core.validators.validate_level]),
        ),
    ]
